MvcNet/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Post.Domain.Models;

namespace MvcNet.Controllers {
    [Authorize]
    public class PostController : Controller {
        private readonly ILogger<PostController> _log;
        private readonly AppDBContext _db;
        public PostController(ILogger<PostController> logger,
                        AppDBContext db) {
            _log = logger;
            _db = db;
        }

        [HttpGet("/Post")]
        public ActionResult Index() {
            var data = _db.posts.Include(d => d.comments).ToList();
            return View("/Views/Post/Index.cshtml",data);
        }

        [HttpGet("/Post/new")]
        public ActionResult NewPost() {
            return View();
        }

        [HttpPost("/Post/new")]
        public async Task<ActionResult> SaveNewPost(PostModel data) {
            _db.posts.Add(data);
            await _db.SaveChangesAsync();
            TempData["message"] = "Success Add Post";
            _log.LogInformation("coba");
            return Redirect("~/Post/new");
        }

        [HttpGet("/Post/{id}/delete")]
        public async Task<ActionResult> DeletePost(int id) {
            // @see  https://stackoverflow.com/a/56537176/4906348
            var post = new PostModel {
                id = id
            };
            _db.posts.Remove(post);
            await _db.SaveChangesAsync();
            TempData["message"] = "Success Delete Post";
            return Redirect("~/Post");
        }

        [HttpGet("/Post/{id}")]
        public ActionResult UpdatePost(int id) {
            var data = _db.posts.Where(i => i.id == id).Single();

            return View("/Views/Post/EditPost.cshtml",data);
        }

        [HttpPost("/Post/{id}")]
        public async Task<ActionResult> UpdatePostData(int id, PostModel data) {
            _db.posts.Update(data);
            TempData["message"] = "Success Update Post";
            await _db.SaveChangesAsync();
            
            return View("/Views/Post/EditPost.cshtml",data);
        }

        [HttpGet("/Post/{id}/Comment")]
        public ActionResult ListCommentModeration(int id)
        {
            var post = _db.posts
                .Include(d => d.comments)
                .First(d => d.id == id);

            return View("/Views/Post/CommentModeration.cshtml", post);
        }   

        [HttpGet("/Post/{id}/comment/{idComment}")]
        public async Task<ActionResult> DeleteComment(int idComment, int id)
        {
            var comment = _db.commentModels.Find(idComment);
            if (comment != null)
            {                
                _db.commentModels.Remove(comment);
                await _db.SaveChangesAsync();
            }
            TempData["message"] = "Success Delete Comment";

            return Redirect("~/Post/"+id.ToString());
        }
    }
}

MvcNet/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MvcNet.Areas.Identity.Data;
using MvcNet.Models.Request;
using System.Text.Encodings.Web;

namespace MvcNet.Controllers {
    public class UserController : Controller {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDBContext _db;

        private readonly MvcNetIdentityDbContext _idb;
        private readonly UserManager<IdentityUser> _userManager;

        public UserController(ILogger<HomeController> logger,
                            AppDBContext db,
                            MvcNetIdentityDbContext idx, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _db = db;
            _idb = idx;
            _userManager = userManager;
        }

        [HttpGet("/login")]
        public IActionResult Login() {
            return View();
        }
        
        /// @ see https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0#require-antiforgery-validation
        [HttpPost("/login")]
        [ValidateAntiForgeryToken]
        public IActionResult LoginPost(string user, string pass) {
            ViewData["user"] = user;
            ViewData["pass"] = pass;
            return View(new {data = user});
        }

        [HttpGet("/User")]
        public IActionResult ListUser()
        {
            var users = _idb.Users.ToList();

            return View("/Views/User/ListUser.cshtml", users);
        }

        [Authorize]
        [HttpGet("/User/{id}")]
        public IActionResult FormEditUser(string id)
        {
            var user = _idb.Users.Find(id);

            return View("/Views/User/EditUser.cshtml", user);
        }

        [Authorize]
        [HttpPost("/User/{id}/Password")]
        public async Task<IActionResult> EditPassword(string id, [FromForm] EditPasswordRequest body)
        {
            if (body.newPassword != body.confirmNewPassword)
            {
                return RedirectToAction("FormEditUser",new {id = id});
            }

            var user = await _idb.Users.FindAsync(id);
            if (user == null) 
            {
                return NotFound();
            }

            // Update pass when success
            string resetToken = await _userManager.GeneratePasswordResetTokenAsync(user);
            var result = await _userManager.ResetPasswordAsync(user, resetToken, body.newPassword);
            if (result.Succeeded)
            {
                TempData["message"] = "Success Change Password";
            }
            else 
            {
                TempData["message"] = "Failed Change Password : " + result.Errors.ToString();
            }

            return RedirectToAction("ListUser");
        }
    }
}

MvcNet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact US</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="~/Home/Blog">Blog</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) || User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Master Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="ListUser">Master User</a>
                            </li>
                            <li class="nav-item">
                                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>