MvcNet/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcNet.Controllers {
  public class TagController : Controller {
    private readonly AppDBContext _db;
    private readonly ILogger<TagController> _log;

    public TagController(ILogger<TagController> log, AppDBContext db) {
      _log = log;
      _db = db; 
    }

    public IActionResult Coba() {
      return Ok();
    }
  }
}

MvcNet/Controllers/TagsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcNet;
using MvcNet.Models;

namespace MvcNet.Controllers
{
    public class TagsController : Controller
    {
        private readonly AppDBContext _context;
        private readonly ILogger<TagsController> _log;

        public TagsController(AppDBContext context, ILogger<TagsController> log)
        {
            _context = context;
            _log = log;
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
            return View(await _context.tags.ToListAsync());
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tagModel = await _context.tags
                .FirstOrDefaultAsync(m => m.id == id);
            if (tagModel == null)
            {
                return NotFound();
            }

            return View(tagModel);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,tagName")] TagModel tagModel)
        {
            _log.LogError("Error");
            if (ModelState.IsValid)
            {
              _context.Add(tagModel);
              await _context.SaveChangesAsync();
              return RedirectToAction(nameof(Index));
            } else {
                _log.LogInformation("err0r");
              foreach (var modelState in ViewData.ModelState.Values)
              {
                  TempData["error"] = modelState.Errors; 
                  foreach (ModelError error in modelState.Errors)
                  {
                      _log.LogInformation(error.ErrorMessage);
                  }
              }
            }
            return View(tagModel);
        }

        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tagModel = await _context.tags.FindAsync(id);
            if (tagModel == null)
            {
                return NotFound();
            }
            return View(tagModel);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,tagName")] TagModel tagModel)
        {
            if (id != tagModel.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tagModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagModelExists(tagModel.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tagModel);
        }

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tagModel = await _context.tags
                .FirstOrDefaultAsync(m => m.id == id);
            if (tagModel == null)
            {
                return NotFound();
            }

            return View(tagModel);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tagModel = await _context.tags.FindAsync(id);
            _context.tags.Remove(tagModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagModelExists(int id)
        {
            return _context.tags.Any(e => e.id == id);
        }
    }
}

MvcNet/Views/Tags/Create.cshtml
@model MvcNet.Models.TagModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TagModel</h4>
@if(TempData["error"] != null) 
{
  @foreach(var i in TempData["error"] as Microsoft.AspNetCore.Mvc.ModelBinding.ModelErrorCollection) {
    @i.ErrorMessage
  }
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="tagName" class="control-label"></label>
                <input asp-for="tagName" class="form-control" />
                <span asp-validation-for="tagName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcNet/Views/Tags/Delete.cshtml
@model MvcNet.Models.TagModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TagModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tagName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tagName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcNet/Views/Tags/Details.cshtml
@model MvcNet.Models.TagModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TagModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tagName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tagName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcNet/Views/Tags/Edit.cshtml
@model MvcNet.Models.TagModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TagModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Tags">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="tagName" class="control-label"></label>
                <input asp-for="tagName" class="form-control" />
                <span asp-validation-for="tagName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcNet/Views/Tags/Index.cshtml
@model IEnumerable<MvcNet.Models.TagModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.tagName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tagName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>